/*
db.employees.find()
db.employees.find({ name: "Steve" })
db.employees.find({ age: { $gt: 30 } }).pretty()
db.employees.find({ "phone.ext": "2143").pretty()
db.employees.find({ age: { $lte: 30 } }).pretty()
db.employees.find({ "favorites.food": "pizza" }).pretty()
db.employees.updateOne({ "name": "Willy" }, { $set: { "phone.personal": "93-123-45-67" } })
db.employees.updateOne({ "name": "Bob" }, { $set: { "privileges": "user" } })
db.employees.find({ "favorites.artist": "Picasso" })
db.employees.deleteOne({ "name": "John" })

db.restaurants.find().pretty()
db.restaurants.find({}, { name: 1, _id: 1, borough: 1, cuisine: 1 }).pretty()
db.restaurants.find({}, { name: 1, _id: 1, borough: 1, "address.zipcode": 1 }).pretty()
db.restaurants.find({ "borough": "Bronx" }).pretty()
db.restaurants.find({ "borough": "Brooklyn", "cuisine":"Steak" }).pretty()
db.restaurants.find({ "grades.score": { $gt: 90 } }).pretty()
db.restaurants.find({ "cuisine": { $ne: "Bakery" } }).pretty()
db.restaurants.find({ "cuisine": { $ne: "Chinese" }, "grades.grade": "A", "borough": { $ne: "Manhattan" } }).pretty()
db.restaurants.updateMany({ "cuisine": "American " }, { $set: { "cuisine": "American" } })
db.restaurants.updateOne({ "name": "Morris Park Bake Shop" }, { $set: { "adress.street": "calle false 123" } })
db.restaurants.deleteMany({ "address.zipcode": "10466" })
*/